#!/usr/bin/env python3
"""
Pickle File Reader for All-Layer Analysis Results.
This script helps you read and explore the pkl files generated by the all-layer analysis.
"""

import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import argparse
from typing import Dict, Any
import sys

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.append(str(project_root))

from XAI_Enhancer_module.utils.directory_manager import create_model_output_dirs


def load_analysis_results(pkl_path: str) -> Dict[str, Any]:
    """
    Load the analysis results from a pickle file.
    
    Args:
        pkl_path: Path to the pickle file
        
    Returns:
        Dictionary containing the analysis results
    """
    try:
        with open(pkl_path, 'rb') as f:
            results = pickle.load(f)
        print(f"✅ Successfully loaded results from: {pkl_path}")
        return results
    except Exception as e:
        print(f"❌ Error loading pickle file: {e}")
        return None


def explore_results_structure(results: Dict[str, Any]):
    """
    Explore and print the structure of the results dictionary.
    
    Args:
        results: The loaded results dictionary
    """
    print(f"\n{'='*60}")
    print("RESULTS STRUCTURE EXPLORATION")
    print(f"{'='*60}")
    
    print(f"Main keys in results: {list(results.keys())}")
    
    for key, value in results.items():
        print(f"\n📋 Key: '{key}'")
        print(f"   Type: {type(value)}")
        
        if isinstance(value, dict):
            print(f"   Sub-keys: {list(value.keys())}")
        elif isinstance(value, list):
            print(f"   Length: {len(value)}")
            if value and isinstance(value[0], dict):
                print(f"   First item keys: {list(value[0].keys())}")
        elif isinstance(value, np.ndarray):
            print(f"   Shape: {value.shape}")
            print(f"   Data type: {value.dtype}")
        else:
            print(f"   Value preview: {str(value)[:100]}...")


def print_evaluation_metrics(results: Dict[str, Any]):
    """
    Print the evaluation metrics in a formatted way.
    
    Args:
        results: The loaded results dictionary
    """
    print(f"\n{'='*60}")
    print("EVALUATION METRICS")
    print(f"{'='*60}")
    
    if 'evaluation_metrics' in results:
        metrics = results['evaluation_metrics']
        
        print(f"Model: {metrics.get('model_name', 'Unknown')}")
        print(f"CAM Method: {metrics.get('cam_method', 'Unknown')}")
        print(f"Layer Mode: {metrics.get('layer_mode', 'Unknown')}")
        print(f"Number of Layers: {metrics.get('num_layers', 'Unknown')}")
        print(f"Images Evaluated: {metrics.get('num_images', 'Unknown')}")
        print(f"Step Size: {metrics.get('step_size', 'Unknown')}")
        
        print(f"\n📊 Performance Metrics:")
        print(f"   Insertion AUC: {metrics.get('insertion_auc_mean', 0):.4f} ± {metrics.get('insertion_auc_std', 0):.4f}")
        print(f"   Deletion AUC:  {metrics.get('deletion_auc_mean', 0):.4f} ± {metrics.get('deletion_auc_std', 0):.4f}")
        print(f"   ROAD Score:    {metrics.get('road_mean', 0):.4f} ± {metrics.get('road_std', 0):.4f}")
        
        # Individual scores
        if 'insertion_aucs' in metrics:
            print(f"\n📈 Individual Insertion AUCs: {metrics['insertion_aucs']}")
        if 'deletion_aucs' in metrics:
            print(f"📉 Individual Deletion AUCs: {metrics['deletion_aucs']}")
        if 'road_scores' in metrics:
            print(f"🛣️  Individual ROAD Scores: {metrics['road_scores']}")


def print_layer_information(results: Dict[str, Any]):
    """
    Print detailed information about the layers.
    
    Args:
        results: The loaded results dictionary
    """
    print(f"\n{'='*60}")
    print("LAYER INFORMATION")
    print(f"{'='*60}")
    
    if 'layer_info' in results:
        layer_info = results['layer_info']
        
        print(f"Total Layers: {len(layer_info)}")
        
        # Create a summary table
        data = []
        for i, layer in enumerate(layer_info):
            data.append({
                'Index': i,
                'Name': layer.get('name', 'Unknown'),
                'Type': layer.get('type', 'Unknown'),
                'In Channels': layer.get('in_channels', 'Unknown'),
                'Out Channels': layer.get('out_channels', 'Unknown'),
                'Kernel Size': layer.get('kernel_size', 'Unknown'),
                'Stride': layer.get('stride', 'Unknown'),
                'Padding': layer.get('padding', 'Unknown')
            })
        
        df = pd.DataFrame(data)
        print(f"\n📋 Layer Details:")
        print(df.to_string(index=False))


def analyze_layer_weights(results: Dict[str, Any]):
    """
    Analyze and display layer weight information.
    
    Args:
        results: The loaded results dictionary
    """
    print(f"\n{'='*60}")
    print("LAYER WEIGHTS ANALYSIS")
    print(f"{'='*60}")
    
    if 'average_weights' in results and results['average_weights'] is not None:
        avg_weights = results['average_weights']
        layer_weights_all = results.get('layer_weights_all', [])
        
        print(f"Average Weights Shape: {avg_weights.shape}")
        print(f"Number of Images Analyzed: {len(layer_weights_all)}")
        
        # Statistics
        print(f"\n📊 Weight Statistics:")
        print(f"   Mean: {np.mean(avg_weights):.6f}")
        print(f"   Std:  {np.std(avg_weights):.6f}")
        print(f"   Min:  {np.min(avg_weights):.6f}")
        print(f"   Max:  {np.max(avg_weights):.6f}")
        
        # Top and bottom layers
        top_5_indices = np.argsort(avg_weights)[-5:][::-1]
        bottom_5_indices = np.argsort(avg_weights)[:5]
        
        print(f"\n🔝 Top 5 Most Important Layers:")
        for rank, idx in enumerate(top_5_indices, 1):
            print(f"   {rank}. Layer {idx}: Weight = {avg_weights[idx]:.6f}")
        
        print(f"\n🔻 Bottom 5 Least Important Layers:")
        for rank, idx in enumerate(bottom_5_indices, 1):
            print(f"   {rank}. Layer {idx}: Weight = {avg_weights[idx]:.6f}")
        
        # Weight distribution across images
        if layer_weights_all:
            weights_matrix = np.array(layer_weights_all)
            print(f"\n📈 Weight Variance Across Images:")
            weight_std = np.std(weights_matrix, axis=0)
            most_variable_layers = np.argsort(weight_std)[-3:][::-1]
            print(f"   Most variable layers: {most_variable_layers}")
            for idx in most_variable_layers:
                print(f"     Layer {idx}: Std = {weight_std[idx]:.6f}")


def export_to_csv(results: Dict[str, Any], output_path: str):
    """
    Export key results to CSV files for further analysis.
    Uses model-specific subdirectories for organization.
    
    Args:
        results: The loaded results dictionary
        output_path: Base directory to save CSV files
    """
    # Extract model name from results, with fallback
    model_name = "unknown_model"
    if 'evaluation_metrics' in results and results['evaluation_metrics']:
        model_name = results['evaluation_metrics'].get('model_name', model_name)
    elif 'model_name' in results:
        model_name = results['model_name']
    
    # Create model-specific CSV directory
    _, model_csv_dir = create_model_output_dirs(
        model_name, 
        base_csv_dir=output_path
    )
    
    print(f"📁 Exporting CSV files to model-specific directory: {model_csv_dir}")
    
    try:
        # Export layer information
        if 'layer_info' in results:
            layer_df = pd.DataFrame(results['layer_info'])
            # Remove the 'module' column as it contains PyTorch objects
            if 'module' in layer_df.columns:
                layer_df = layer_df.drop('module', axis=1)
            layer_csv_path = model_csv_dir / "layer_information.csv"
            layer_df.to_csv(layer_csv_path, index=False)
            print(f"✅ Layer information exported to: {layer_csv_path}")
        
        # Export average weights
        if 'average_weights' in results and results['average_weights'] is not None:
            weights_df = pd.DataFrame({
                'Layer_Index': range(len(results['average_weights'])),
                'Average_Weight': results['average_weights']
            })
            weights_csv_path = model_csv_dir / "layer_weights.csv"
            weights_df.to_csv(weights_csv_path, index=False)
            print(f"✅ Layer weights exported to: {weights_csv_path}")
        
        # Export evaluation metrics
        if 'evaluation_metrics' in results:
            metrics = results['evaluation_metrics']
            # Create a single-row DataFrame with metrics
            metrics_df = pd.DataFrame([{
                'model_name': metrics.get('model_name'),
                'cam_method': metrics.get('cam_method'),
                'layer_mode': metrics.get('layer_mode'),
                'num_layers': metrics.get('num_layers'),
                'num_images': metrics.get('num_images'),
                'insertion_auc_mean': metrics.get('insertion_auc_mean'),
                'insertion_auc_std': metrics.get('insertion_auc_std'),
                'deletion_auc_mean': metrics.get('deletion_auc_mean'),
                'deletion_auc_std': metrics.get('deletion_auc_std'),
                'road_mean': metrics.get('road_mean'),
                'road_std': metrics.get('road_std')
            }])
            metrics_csv_path = model_csv_dir / "evaluation_metrics.csv"
            metrics_df.to_csv(metrics_csv_path, index=False)
            print(f"✅ Evaluation metrics exported to: {metrics_csv_path}")
            
    except Exception as e:
        print(f"❌ Error exporting to CSV: {e}")


def create_weight_plot(results: Dict[str, Any], save_path: str = None):
    """
    Create a simple plot of the layer weights.
    
    Args:
        results: The loaded results dictionary
        save_path: Optional path to save the plot
    """
    if 'average_weights' not in results or results['average_weights'] is None:
        print("No weight data available for plotting")
        return
    
    avg_weights = results['average_weights']
    layer_indices = range(len(avg_weights))
    
    plt.figure(figsize=(12, 6))
    
    # Bar plot of weights
    bars = plt.bar(layer_indices, avg_weights, alpha=0.7, color='skyblue', edgecolor='navy')
    
    # Highlight top 3 layers
    top_3_indices = np.argsort(avg_weights)[-3:]
    for idx in top_3_indices:
        bars[idx].set_color('orange')
    
    plt.title('Layer Weights from Pickle File', fontsize=14, fontweight='bold')
    plt.xlabel('Layer Index')
    plt.ylabel('Average Weight')
    plt.grid(True, alpha=0.3)
    
    # Add value labels on top bars
    for i, weight in enumerate(avg_weights):
        if weight > np.max(avg_weights) * 0.8:  # Only label top weights
            plt.text(i, weight + np.max(avg_weights) * 0.01, f'{weight:.4f}', 
                    ha='center', va='bottom', fontsize=8)
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"✅ Weight plot saved to: {save_path}")
    
    plt.show()


def main():
    """Main function with argument parsing."""
    parser = argparse.ArgumentParser(
        description="Read and explore pickle files from all-layer analysis",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic exploration
  python read_pkl.py analysis_results/resnet18_analysis_results.pkl

  # Detailed analysis with CSV export
  python read_pkl.py analysis_results/resnet18_analysis_results.pkl --export-csv --output-dir csv_exports

  # Quick summary only
  python read_pkl.py analysis_results/resnet18_analysis_results.pkl --summary-only

  # Create weight plot
  python read_pkl.py analysis_results/resnet18_analysis_results.pkl --plot-weights
        """
    )
    
    parser.add_argument('pkl_file', help='Path to the pickle file')
    
    parser.add_argument('--summary-only', action='store_true',
                       help='Show only summary information')
    
    parser.add_argument('--export-csv', action='store_true',
                       help='Export data to CSV files')
    
    parser.add_argument('--output-dir', default='./csv_exports',
                       help='Directory for CSV exports')
    
    parser.add_argument('--plot-weights', action='store_true',
                       help='Create a plot of layer weights')
    
    parser.add_argument('--save-plot', 
                       help='Path to save the weight plot')
    
    args = parser.parse_args()
    
    # Check if file exists
    if not Path(args.pkl_file).exists():
        print(f"❌ File not found: {args.pkl_file}")
        return
    
    print(f"\n{'='*80}")
    print("PICKLE FILE READER - ALL-LAYER ANALYSIS RESULTS")
    print(f"{'='*80}")
    print(f"Reading file: {args.pkl_file}")
    
    # Load the results
    results = load_analysis_results(args.pkl_file)
    if results is None:
        return
    
    # Explore structure
    explore_results_structure(results)
    
    if not args.summary_only:
        # Print detailed information
        print_evaluation_metrics(results)
        print_layer_information(results)
        analyze_layer_weights(results)
    
    # Export to CSV if requested
    if args.export_csv:
        export_to_csv(results, args.output_dir)
    
    # Create weight plot if requested
    if args.plot_weights:
        create_weight_plot(results, args.save_plot)
    
    print(f"\n✅ Analysis completed!")


if __name__ == "__main__":
    main()
